### PR TITLE
LTD-5128 Python3.9 upgrade

### PR DESCRIPTION
**Pull request by markj0hnst0n**
Python3.9 upgrade and add typing-extensions package to ensure compatibility.

This has been deployed on the uat environment and tested manually.  Results below.

Manual test case scenarios carried out using `resend_edi_data_email.py` management command:

- EDI data email sent from Spire and ingested by Lite HMRC system with correct db information (PASS)
- EDI data email sent on from Lite HMRC on to HMRC mailbox (PASS)
- LITE API call simulated and Email sent from Lite HMRC to HMRC mailbox (PASS)

Other manual testing:

- Health check viewed (PASS)
- Checked mailbox connections with `mail/management/commands/check_mailserver_connections.py` managment command (PASS)

### CODE REVIEW

**Comment by depsiatwal** [comment]
Has this been deployed any where ?

**Comment by markj0hnst0n** [comment]
it's been deployed on dev2 for a while @depsiatwal

**Comment by saruniitr** [comment]
> Has this been deployed any where ? also @saruniitr or @currycoder any suggestions on testing this ? similar to when we shifted to celery

@markj0hnst0n @depsiatwal With celery all tasks were affected so tested all of them on UAT.
All of the testing is manual, there are test mailboxes attached to environments so we can use them to send licence data and reply messages as well.

**Comment by seijihg** [comment]
hehe if this just happened earlier :D had some stuffs earlier where I needed 3.9 instead of making a work around because we were on 3.8 xD

**Review by hnryjmes — COMMENTED** [review]
agree with Arun's comment, if you can use the mailboxes we have for use with the UAT environment and simulate some licence mails that should be a good test of the version upgrade. but I think I don't know quite how to do that myself (!)

**Review by kevincarrogan — APPROVED** [review]

**Review by saruniitr — APPROVED** [review]

**Pull request merged**
